### ISSUE TITLE
PD Aircraft

### ISSUE THREAD

**Issue by KeNolan28** [WPTK/awesome-planespotting-list#1]
New Hampshire State Police
NHSP Bell 407 N366SP A42434
NHSP Cessna 182T N366NH A423CA

CT State and Fairfield County
CSP Bell 407 N1903A A16AED
Fairfield County (registered under Stratford PD) Eagle 1 Bell UH-1 N93ND Ace480

TY,
Ken

**Comment by WPTK** [comment]
Done, will push changes soon.
